CFLAGS = -O3
CC = nvcc

#insert the ignore for deprecated gpu targets if using CUDA 8.0
CFLAGS += $(shell if [ `nvcc --version | grep 8.0 | wc -l` != 0 ]; then echo -Wno-deprecated-gpu-targets ; fi)

all: matrix_sum

matrix_sum: timer.o matrix_sum.o
	$(CC) $(CFLAGS) -o matrix_sum timer.o matrix_sum.o

clean:
	rm -f *.o matrix_sum

%.o: %.cc
	$(CC) $(CFLAGS) -o $@ -c $<

%.o: %.cu
	$(CC) $(CFLAGS) -o $@ -c $<
